<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>自定义 Promise</title>
  </head>
  <body>
    <script src="./lib/Promise.js"></script>
    <!-- <script>
      let p = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(1) // value
          // 表明执行完 resolve 后，回调函数是异步执行的
          console.log('resolve() 执行完成后')
          // reject(2) // reason
        }, 100)
      })
      p.then(
        value => {
          console.log('onResolved1():', value)
        },
        reason => {
          console.log('onRejected1():', reason)
        },
      )
      p.then(
        value => {
          console.log('onResolved2():', value)
        },
        reason => {
          console.log('onRejected2():', reason)
        },
      )
    </script> -->
    <!-- Promise then链式操作测试 -->
    <!-- <script>
      let p = new Promise((resolve, reject) => {
        setTimeout(() => {
          // resolve(1) // value
          reject(2) // reason
        }, 100)
      })
        .then(
          value => {
            console.log('onResolved1():', value)
            return 2
          },
          reason => {
            console.log('onRejected1():', reason)
            throw 3
            // return new Promise((resolve, reject) => reject(4))
            // return 5
          },
        )
        .then(
          value => {
            console.log('onResolved2():', value)
          },
          reason => {
            console.log('onRejected2():', reason)
            throw 6
          },
        )
        .catch(reason => {
          console.log('onRejected3()', reason)
          // return 7
          // throw 8
          return new Promise(() => {}) // 中断 promise 链
        })
        .then(
          value => {
            console.log('onResolved4():', value)
          },
          reason => {
            console.log('onRejected4():', reason)
          },
        )
    </script> -->

    <!-- Promise resolve 和 reject 测试 -->
    <!-- <script>
      const p1 = Promise.resolve(2)
      const p2 = Promise.resolve(Promise.resolve(3))
      const p3 = Promise.resolve(Promise.reject(4))
      p1.then(value => {
        console.log('p1:', value)
      })
      p2.then(value => {
        console.log('p2:', value)
      })
      p3.catch(reason => {
        console.log('p3:', reason)
      })
    </script> -->

    <!-- Promise all 和 race 的测试 -->
    <script>
      const p1 = Promise.resolve(2)
      const p2 = Promise.resolve(Promise.resolve(3))
      // const p3 = Promise.resolve(Promise.reject(4))
      const p3 = Promise.reject(4)
      const p4 = new Promise((resolve, reject) => {
        setTimeout(() => {
          resolve(5)
        }, 100)
      })
      const pAll = Promise.all([p4, p1, p2, 6])
      pAll.then(
        value => {
          console.log('pAll onResolved()', value)
        },
        reason => {
          console.log('pAll onRejected()', reason)
        },
      )

      const pRace = Promise.race([p3, p1, p2, 7])
      pRace.then(
        value => {
          console.log('pRace onResolved()', value)
        },
        reason => {
          console.log('pRace onRejected()', reason)
        },
      )
    </script>
  </body>
</html>
